version: "2"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - 8090:5672
      - 5672:5672
      - 15672:15672
  db:
    container_name: db
    image: mongo
    ports:
      - 27017:27017